services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel_db_container
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotel_db
      MYSQL_USER: hotel_user
      MYSQL_PASSWORD: hotel_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
